### ISSUE TITLE
1.18 and newer versions

### ISSUE THREAD

**Issue by WilczaQ** [TheWii/immersive-soundscapes#7]
Datapack does not work well on newer versions. For example, I'm at level Y 94 in a savanna biome and I hear ambient from an abandoned mine. Additionally, of course, the sounds from level 0 to level -64 and from level 254 upwards do not work. Will this datapack still be supported?

**Comment by VenusVesper** [comment]
Yes the same is happening to my game, are you going to update to 1.19

**Comment by LouisLecouturier** [comment]
> Yes the same is happening to my game, are you going to update to 1.19

Last commit was 2 years ago so I'm afraid it's no longer maintained

**Comment by TheWii** [comment]
Hello! Yeah, the data pack has been unmaintained for 2 years. Regarding 1.18 and 1.19 compatibility, I'm coming up with a hot fix since these updates completely broke the pack, although i'm sure I won't be able to recover cave ambience completely because the current method I use to detect if a player is in a cave doesn't work anymore (caves no longer generate with `cave_air`).

**Comment by WilczaQ** [comment]
I understand, we will wait for a fix :)

**Comment by TheWii** [comment]
Just released it!
https://github.com/TheWii/immersive-soundscapes/releases/tag/v2.5

I'm marking this as solved ;)
